name: Docker registry

on: 
 push:
   tags:
    - "*"

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :tag
        if: success()
        run: docker build -t koukidan/folio-bot:latest -t koukidan/folio-bot:${IMAGE_TAG} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push koukidan/folio-bot:${IMAGE_TAG}
      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push koukidan/folio-bot:latest

